// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview AI-powered tag suggestion for submitted resources.
 *
 * - suggestResourceTags - A function that suggests relevant tags/categories for a given resource.
 * - SuggestResourceTagsInput - The input type for the suggestResourceTags function.
 * - SuggestResourceTagsOutput - The return type for the suggestResourceTags function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestResourceTagsInputSchema = z.object({
  resourceTitle: z.string().describe('The title of the resource.'),
  resourceDescription: z.string().describe('A detailed description of the resource.'),
});
export type SuggestResourceTagsInput = z.infer<typeof SuggestResourceTagsInputSchema>;

const SuggestResourceTagsOutputSchema = z.object({
  suggestedTags: z
    .array(z.string())
    .describe('An array of suggested tags/categories for the resource.'),
});
export type SuggestResourceTagsOutput = z.infer<typeof SuggestResourceTagsOutputSchema>;

export async function suggestResourceTags(input: SuggestResourceTagsInput): Promise<SuggestResourceTagsOutput> {
  return suggestResourceTagsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestResourceTagsPrompt',
  input: {schema: SuggestResourceTagsInputSchema},
  output: {schema: SuggestResourceTagsOutputSchema},
  prompt: `You are an expert in resource categorization. Given the title and description of a resource, you will suggest relevant tags/categories.

Title: {{{resourceTitle}}}
Description: {{{resourceDescription}}}

Suggest at least 3 tags that would be relevant to this resource:
`,config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const suggestResourceTagsFlow = ai.defineFlow(
  {
    name: 'suggestResourceTagsFlow',
    inputSchema: SuggestResourceTagsInputSchema,
    outputSchema: SuggestResourceTagsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
